{1}{}{PID_METAL_PARTS@Varias piezas irregulares de metal, de todas las formas y tamaños. Nada especial, pero supones que podría convertirse en algo que valga la pena dada la experiencia y el equipo adecuados.@@@PID_METAL_ORE 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_METAL_PARTS 1@exp 10 script fix_boy@fix_Resource}
{2}{}{PID_GUNPOWDER@Una caja con un polvo negro.@@@PID_MINERAL 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_GUNPOWDER 1@exp 5 script fix_boy@fix_Resource}
{3}{}{PID_ALLOYS@Algunas aleaciones Puede usarlos para reparar y actualizar equipos, o cualquier otro proyecto de ingeniería.@@@PID_MINERAL 2&PID_METAL_ORE 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_ALLOYS 1@exp 20 script fix_boy@fix_Resource}
{4}{}{PID_METAL_PARTS2@Varias piezas irregulares de buen metal, todas las formas y tamaños. Nada especial, pero supones que podría convertirse en algo que valga la pena dada la experiencia y el equipo adecuados.@@@PID_ORE2 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_METAL_PARTS2 1@exp 10 script fix_boy@fix_Resource}
{5}{}{PID_GUNPOWDER2@Una caja con un mejor polvo negro.@@@PID_MINERALS2 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_GUNPOWDER2 1@exp 10 script fix_boy@fix_Resource}
{6}{}{PID_ALLOYS2@Aleaciones de muy buena calidad. Puede usarlos para reparar y actualizar equipos, o cualquier otro proyecto de ingeniería.@@@PID_MINERALS2 1&PID_ORE2 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_ALLOYS2 1@exp 20 script fix_boy@fix_Resource}
{7}{}{PID_SAND_ROBE@Una túnica genérica de color arena.@@@PID_FIBER 3&PID_GECKO_PELT 1&PID_BRAHMIN_HIDE 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SAND_ROBE 1@exp 120 script fix_boy@fix_Generic}
{8}{}{PID_PURPLE_ROBE@Una túnica genérica de color púrpura.@@@PID_FIBER 3&PID_GOLDEN_GECKO_PELT 1&PID_BRAHMIN_HIDE 1&PID_CHEMICALS 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_PURPLE_ROBE 1@exp 200 script fix_boy@fix_Generic}
{9}{}{PID_LEATHER_JACKET@Una chaqueta negra de cuero pesado.@@@PID_FIBER 1&PID_GECKO_PELT 5@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_LEATHER_JACKET 1&PID_LEATHER_JACKET_HELMET 1@exp 250 script fix_boy@fix_Generic}
{10}{}{PID_CURED_LEATHER_ARMOR@Esta chaqueta de cuero muy acolchada es inusual porque tiene dos mangas. Definitivamente harás una declaración de moda cuando y donde sea que retumbes.@PE_PROFESSION_ARMORER 1@PE_PROFESSION_ARMORER 2@PID_FIBER 1&PID_GECKO_PELT 5&PID_GOLDEN_GECKO_PELT 1&PID_LEATHER_JACKET 1&PID_LEATHER_JACKET_HELMET 1&PID_BLUEPRINT_COMBAT_JACKET 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_CURED_LEATHER_ARMOR 1&PID_COMBAT_LEATHER_JACKET_HELMET 1@exp 500 script fix_boy@fix_Generic}
{11}{}{PID_LEATHER_ARMOR@Su armadura básica de cuero. Finamente elaborado de piel de brahmin curtido.@PE_PROFESSION_ARMORER 1@PE_PROFESSION_ARMORER 1@PID_FIBER 1&PID_GOLDEN_GECKO_PELT 5@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_LEATHER_ARMOR 1&PID_LEATHER_ARMOR_HELMET 1@exp 300 script fix_boy@fix_Generic}
{12}{}{PID_LEATHER_ARMOR_MK_II@Una versión mejorada de la armadura de cuero básica con capas adicionales de protección. Finamente elaborado a partir de piel de brahmin curtido.@PE_PROFESSION_ARMORER 1@PE_PROFESSION_ARMORER 1&SK_REPAIR 80@PID_LEATHER_ARMOR 1&PID_GOLDEN_GECKO_PELT 1&PID_FIBER 2&PID_BRAHMIN_HIDE 1&PID_LEATHER_ARMOR_HELMET 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_LEATHER_ARMOR_MK_II 1&PID_LEATHER_ARMOR_HELMET_MK2 1@exp 400 script fix_boy@fix_Generic}
{13}{}{PID_FIREGECKO_JACKET@Armadura de cuero altamente resistente al fuego hecha de piel de gecko de fuego.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 80@PID_LEATHER_ARMOR 1&PID_FIREGECKO_PELT 1&PID_FIBER 2&PID_LEATHER_ARMOR_HELMET 1&PID_BLUEPRINT_FIREGECKO_JACKET 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_FIREGECKO_JACKET 1&PID_LEATHER_ARMOR_HELMET_MK2 1@exp 500 script fix_boy@fix_Generic}
{14}{}{PID_METAL_ARMOR@Placas de metal pulido, formando crudamente una armadura.@PE_PROFESSION_ARMORER 1@PE_PROFESSION_ARMORER 1&SK_REPAIR 100@PID_FIBER 1&PID_BRAHMIN_HIDE 1&PID_METAL_PARTS 4&PID_ALLOYS 3@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_METAL_ARMOR 1&PID_METAL_HELMET 1@exp 250 script fix_boy@fix_Generic}
{15}{}{PID_METAL_ARMOR_MK_II@Placas de metal pulido, finamente confeccionadas en una armadura de metal mas brillosa.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_METAL_PARTS2 3&PID_METAL_ARMOR 1&PID_FIBER 1&PID_BLUEPRINT_METAL_ARMOR_MK_II 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_METAL_ARMOR_MK_II 1&PID_METAL_HELMET_MK2 1@exp 1000 script fix_boy@fix_Blueprint}
{16}{}{PID_METAL_ARMOR_MK_III@Un conjunto de armadura metálica reforzada de manera profesional y pesada, esta pieza de artesanía maestra de alta resistencia proporcionará una protección adecuada contra la mayoría de los tipos de daños y una protección excepcional para la mayoría de los ataques basados ​​en láser.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_METAL_ARMOR 1&PID_FIBER 1&PID_ALLOYS2 1&PID_METAL_PARTS2 2&PID_BLUEPRINT_METAL_ARMOR_MK_III 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_POWER_ARMOR 1@PID_METAL_ARMOR_MK_III 1&PID_METAL_HELMET_MK2 1@exp 900 script fix_boy@fix_Blueprint}
{17}{}{PID_TESLA_ARMOR@Esta brillante armadura proporciona una protección superior contra los ataques de energía. Las tres barras de bobina de atracción de Tesla dispersan un gran porcentaje de ataques de energía dirigidos.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_METAL_ARMOR 1&PID_ALLOYS2 1&PID_ELECTRONIC_PARTS 4&PID_BLUEPRINT_TESLA_ARMOR 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_POWER_ARMOR 1@PID_TESLA_ARMOR 1&PID_METAL_HELMET_MK2 1@exp 500 script fix_boy@fix_Blueprint}
{18}{}{PID_INFERNO_ARMOR@Armadura tecnológicamente avanzada, hecha de placas de alta calidad, se han utilizado los componentes resistentes al calor. Tipo de armadura hecha para protección contra incendios y quemaduras.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_METAL_ARMOR 1&PID_ALLOYS2 1&PID_ADV_SUPERBURN 2&PID_BLUEPRINT_INFERNO_ARMOR 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_POWER_ARMOR 1@PID_INFERNO_ARMOR 1&PID_METAL_HELMET_MK2 1@exp 400 script fix_boy@fix_Blueprint}
{19}{}{PID_MUT_METAL@Es una armadura cruda que usa correas de cuero y bandas de metal para formar una cubierta escasa pero efectiva.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_METAL_ARMOR 1&PID_ALLOYS2 2&PID_METAL_PARTS2 2&PID_BLUEPRINT_MUT_ARMOR 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_POWER_ARMOR 1@PID_MUT_METAL 1&PID_METAL_HELMET_MK2 1@exp 1000 script fix_boy@fix_Blueprint}
{20}{}{PID_COMBAT_ARMOR@Armadura de alta tecnología, hecha de polímeros defensivos avanzados.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 1&SK_REPAIR 100@PID_ALLOYS2 3&PID_METAL_PARTS 1&PID_FIBER 1&PID_FIREGECKO_PELT 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_POWER_ARMOR 1@PID_COMBAT_ARMOR 1&PID_COMBAT_HELMET 1@exp 850 script fix_boy@fix_Blueprint}
{21}{}{PID_COMBAT_ARMOR_MK_II@Armadura de alta tecnología, hecha con polímeros defensivos avanzados. Es eficaz contra daño "normal".@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_COMBAT_ARMOR 1&PID_ALLOYS2 3&PID_ALLOYS 3&PID_METAL_PARTS2 3&PID_BLUEPRINT_COMBAT_ARMOR_MK_II 1@PID_ADVANCED_BENCH 1@PID_COMBAT_ARMOR_MK_II 1&PID_COMBAT_HELMET_MK_II 1@exp 1200 script fix_boy@fix_Blueprint}
{22}{}{PID_BROTHERHOOD_COMBAT_ARMOR@Una versión superior de la armadura de combate. La Hermandad del Acero ha realizado muchas mejoras con respecto a la versión estándar. Eficaz contra el plasma.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_COMBAT_ARMOR 1&PID_ALLOYS2 3&PID_ALLOYS 3&PID_ELECTRONIC_PARTS 2&PID_GECKO_PELT 1&PID_BLUEPRINT_BROTHERHOOD_COMBAT_ARMOR 1@PID_ADVANCED_BENCH 1@PID_BROTHERHOOD_COMBAT_ARMOR 1&PID_BROTHERHOOD_HELMET 1@exp 1000 script fix_boy@fix_Blueprint}
{23}{}{PID_ENCLAVE_COMBAT_ARMOR@El prototipo de una versión superior de la armadura de combate, desarrollado por el Enclave. Sus avanzados materiales de policarbonato le permiten una mejor protección contra los ataques de energía.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_COMBAT_ARMOR 1&PID_ALLOYS2 3&PID_ALLOYS 3&PID_ELECTRONIC_PARTS 3&PID_BLUEPRINT_ENCLAVE_COMBAT_ARMOR 1@PID_ADVANCED_BENCH 1@PID_ENCLAVE_COMBAT_ARMOR 1&PID_ENCLAVE_COMBAT_HELMET 1@exp 1000 script fix_boy@fix_Blueprint}
{24}{}{PID_DESERT_COMBAT_ARMOR@Armadura de combate asegurando una mejor protección contra la arena y el polvo durante las operaciones en el desierto. Además, tonos de color arena para un mejor camuflaje.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_COMBAT_ARMOR 1&PID_ALLOYS2 3&PID_ALLOYS 6&PID_BLUEPRINT_DESERT_COMBAT_ARMOR 1@PID_ADVANCED_BENCH 1@PID_DESERT_COMBAT_ARMOR 1&PID_DESERT_COMBAT_HELMET 1@exp 900 script fix_boy@fix_Blueprint}
{25}{}{PID_NCR_ARMOR@Armadura de alta tecnología, hecha de polímeros defensivos avanzados. Este está modificado para los Rangers de la Nueva República de California.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_COMBAT_ARMOR 1&PID_ALLOYS2 3&PID_ALLOYS 3&PID_FIREGECKO_PELT 1&PID_BLUEPRINT_NCR_ARMOR 1@PID_ADVANCED_BENCH 1@PID_NCR_ARMOR 1&PID_NCR_HELMET 1@exp 1000 script fix_boy@fix_Blueprint}
{26}{}{PID_CLOTHES_POLICE@Armadura de combate de Ciudad Refugio hecha de polímeros de alta calidad. Tipo de armadura hecha para protección contra golpes críticos.@PE_PROFESSION_ARMORER 2@PE_PROFESSION_ARMORER 2&SK_REPAIR 130@PID_COMBAT_ARMOR 1&PID_ALLOYS2 6&PID_ALLOYS 3&PID_BLUEPRINT_CLOTHES_POLICE 1@PID_ADVANCED_BENCH 1@PID_CLOTHES_POLICE 1&PID_VC_HELMET 1@exp 1200 script fix_boy@fix_Blueprint}
{27}{}{PID_BBS@Un paquete de municiones BB de antes de la guerra. En excelente condición. Acero inoxidable.@@@PID_PUMP_PARTS 4@@PID_BBS 50@exp 20 script fix_boy@fix_Generic}
{28}{}{PID_9MM_BALL@Una colección de rondas antiguas de 9x19 mm. Grasa pesada para preservarlos del medio ambiente. Balas estándar.@@@PID_METAL_PARTS 1&PID_GUNPOWDER 4&PID_PUMP_PARTS 1@@PID_9MM_BALL 100@exp 90 script fix_boy@fix_Generic}
{29}{}{PID_10MM_JHP@Munición. Calibre: 10 mm, puntas huecas con camisa.@@@PID_METAL_PARTS 1&PID_GUNPOWDER 8@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_10MM_JHP 100@exp 150 script fix_boy@fix_Generic}
{30}{}{PID_10MM_AP@Munición. Calibre: 10 mm, perforación de armadura.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_METAL_PARTS 1&PID_GUNPOWDER 10@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_10MM_AP 100@exp 180 script fix_boy@fix_Generic}
{31}{}{PID_44_MAGNUM_JHP@Un cartucho de municiones, calibre .44 Magnum, puntas huecas.@@@PID_METAL_PARTS 1&PID_GUNPOWDER 10@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_44_MAGNUM_JHP 100@exp 180 script fix_boy@fix_Generic}
{32}{}{PID_44_FMJ_MAGNUM@Un cartucho de municiones, calibre .44 Magnum, chaqueta metálica completa.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_METAL_PARTS 1&PID_GUNPOWDER 10@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_44_FMJ_MAGNUM 100@exp 180 script fix_boy@fix_Generic}
{33}{}{PID_45_CALIBER_AMMO@Munición. Calibre .45.@@@PID_PUMP_PARTS 1&PID_GUNPOWDER 5@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_45_CALIBER_AMMO 100@exp 80 script fix_boy@fix_Generic}
{34}{}{PID_HN_NEEDLER_CARTRIDGE@Munición. Este cartucho parece ser munición para la pistola HN Needler. Cada 'bala' es una pequeña jeringa diseñada para inyectar un objetivo con su contenido en el momento del impacto.@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_DOCTOR 2@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_DOCTOR 2@PID_METAL_PARTS 1&PID_GUNPOWDER2 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_HN_NEEDLER_CARTRIDGE 100@exp 50 script fix_boy@fix_Generic}
{35}{}{PID_HN_AP_NEEDLER_CARTRIDGE@Munición. Este cartucho parece ser una munición perforadora para la pistola HN Needler. Las puntas de las jeringas están hechas de una aleación extraña y son increíblemente afiladas.@PE_PROFESSION_DOCTOR 2|PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_DOCTOR 2|PE_PROFESSION_GUNSMITH_S 2@PID_METAL_PARTS2 1&PID_GUNPOWDER2 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_HN_AP_NEEDLER_CARTRIDGE 100@exp 300 script fix_boy@fix_Generic}
{36}{}{PID_SHOTGUN_SHELLS@12 ga. Cartuchos de escopeta.@@@PID_METAL_PARTS 1&PID_GUNPOWDER 9@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SHOTGUN_SHELLS 100@exp 150 script fix_boy@fix_Generic}
{37}{}{PID_SHOTGUN_SHELLS_SLUG@12 ga. Cartuchos de escopeta (Slug)@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_METAL_PARTS 1&PID_PUMP_PARTS 2&PID_GUNPOWDER2 8@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SHOTGUN_SHELLS_SLUG 100@exp 200 script fix_boy@fix_Generic}
{38}{}{PID_SHOTGUN_SHELLS_FLECHETTE@12 ga. Cartuchos de escopeta (Flechette)@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_PUMP_PARTS 2&PID_METAL_PARTS2 1&PID_GUNPOWDER2 10@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SHOTGUN_SHELLS_FLECHETTE 100@exp 400 script fix_boy@fix_Generic}
{39}{}{PID_SHOTGUN_SHELLS_EMP@12 ga. Cartuchos de escopeta (EMP)@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2&SK_SCIENCE 120@PID_METAL_PARTS2 1&PID_GUNPOWDER2 2&PID_ELECTRONIC_PARTS 4@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SHOTGUN_SHELLS_EMP 100@exp 500 script fix_boy@fix_Generic}
{40}{}{PID_SHOTGUN_DRAGON_BREATH_SHELLS@Municion de fuego para escopetas. Se compone principalmente de perdigones / fragmentos de magnesio. Cuando se dispara la ronda, chispas y llamas pueden dispararse a unos 30 metros.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2&SK_SCIENCE 175@PID_GUNPOWDER3 1&PID_FIREGECKO_PELT 10&PID_BLUEPRINT_SHOTGUN_DRAGON_BREATH_SHELLS 1@PID_ADVANCED_BENCH 1@PID_SHOTGUN_DRAGON_BREATH_SHELLS 100@exp 15000 script fix_boy@fix_Blueprint}
{41}{}{PID_14MM_AP@Municiones de gran calibre. Perforación de armadura de 14 mm.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_METAL_PARTS 1&PID_GUNPOWDER2 4@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_14MM_AP 100@exp 110 script fix_boy@fix_Generic}
{42}{}{PID_223_FMJ@Un cartucho de municiones, calibre .223, Chaqueta de Metal Completa@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 2@PID_METAL_PARTS 1&PID_GUNPOWDER2 5@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_223_FMJ 100@exp 130 script fix_boy@fix_Generic}
{43}{}{PID_5MM_JHP@Una caja de municiones pequeñas y ligeras. Calibre: 5 mm, punta hueca con camisa.@PE_PROFESSION_GUNSMITH_B 1|PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_B 1|PE_PROFESSION_GUNSMITH_S 1@PID_METAL_PARTS 1&PID_GUNPOWDER 4@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_5MM_JHP 100@exp 90 script fix_boy@fix_Generic}
{44}{}{PID_5MM_AP@Una caja de municiones de pequeñas y ligeras. Calibre: 5mm, perforacion de armadura.@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 2@PID_METAL_PARTS 2&PID_GUNPOWDER2 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_5MM_AP 100@exp 80 script fix_boy@fix_Generic}
{45}{}{PID_7_62MM_AMMO@Munición. Calibre: 7.62 mm.@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 1@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 1@PID_METAL_PARTS 1&PID_GUNPOWDER 10@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_7_62MM_AMMO 100@exp 180 script fix_boy@fix_Generic}
{46}{}{PID_40MM_GRENADE@Una granada para un lanzagranadas@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_METAL_PARTS 1&PID_PUMP_PARTS 1&PID_GUNPOWDER 5@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_40MM_GRENADE 10@exp 110 script fix_boy@fix_Generic}
{47}{}{PID_FLAMETHROWER_FUEL@Un cilindro que contiene un combustible líquido extremadamente inflamable para lanzallamas.@@@PID_ROT_GUT 4@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_FLAMETHROWER_FUEL 120@exp 80 script fix_boy@fix_Generic}
{48}{}{PID_ADV_SUPERBURN@Un componente del combustible del lanzallamas. Hace que el combustible sea aún más caliente y peligroso.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_GUNPOWDER2 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_ADV_SUPERBURN 1@exp 40 script fix_boy@fix_Generic}
{49}{}{PID_FLAMETHROWER_FUEL_MK_II@Este combustible de lanzallamas utiliza una mezcla avanzada de supercombustión.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_ADV_SUPERBURN 1&PID_FLAMETHROWER_FUEL 40@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_FLAMETHROWER_FUEL_MK_II 40@exp 80 script fix_boy@fix_Generic}
{50}{}{PID_EXPLOSIVE_ROCKET@Un cohete con una gran ojiva explosiva.@PE_PROFESSION_GUNSMITH_B 1@PE_PROFESSION_GUNSMITH_B 1@PID_METAL_PARTS 1&PID_GUNPOWDER 6&PID_PUMP_PARTS 1@PID_ADVANCED_BENCH 1@PID_EXPLOSIVE_ROCKET 10@exp 125 script fix_boy@fix_Generic}
{51}{}{PID_NAPALM@Este lanzallamas tiene un compresor de alta presión incorporado que aumenta en gran medida su distancia de disparo efectiva y el daño.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_CARBON_POLYMER 1&PID_ROTARY_CHAMBER 2&PID_TECH_SEMI_TRIGGER 1&PID_ABSORBER 1&PID_BLUEPRINT_NAPALM 1@PID_MACHINERY_SMALL_GUNS 1@PID_NAPALM 1@exp 25000 script fix_boy@fix_Blueprint}
{52}{}{PID_ROCKET_AP@Un cohete, con un explosivo más pequeño, pero diseñado para perforar blindaje.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_METAL_PARTS 1&PID_GUNPOWDER2 5&PID_ELECTRONIC_PARTS 1@PID_ADVANCED_BENCH 1@PID_ROCKET_AP 10@exp 180 script fix_boy@fix_Generic}
{53}{}{PID_EL_ROCKET@Este cohete emite un fuerte impulso eléctrico al impactar electrocutando efectivamente a cualquier persona en su radio de explosión.@@@PID_ELECTRONIC_PARTS 2&PID_GUNPOWDER2 5@PID_ADVANCED_BENCH 1@PID_EL_ROCKET 10@exp 200 script fix_boy@fix_Generic}
{54}{}{PID_ROBO_ROCKET_AMMO@Isn't exists in this game yet.@PE_PROFESSION_ENERGY_EXPERT 4|PE_PROFESSION_GUNSMITH_B 4@PE_PROFESSION_ENERGY_EXPERT 4|PE_PROFESSION_GUNSMITH_B 4&SK_SCIENCE 175@PID_METAL_PARTS 7&PID_ALLOYS 15&PID_METAL_PARTS2 9&PID_ALLOYS2 7&PID_GUNPOWDER2 15&PID_ELECTRONIC_PARTS2 7&PID_TECH_CONDEN 7&PID_BLUEPRINT_ROBO_ROCKET_AMMO 1@PID_WORKBENCH_FAT_HI_AMMO 1@PID_ROBO_ROCKET_AMMO 1@exp 300 script fix_boy@fix_Blueprint}
{55}{}{PID_SMALL_ENERGY_CELL@Una unidad de almacenamiento de energía pequeña y autónoma.@@SK_SCIENCE 120@PID_ALLOYS 2&PID_ELECTRONIC_PARTS 4@PID_ADVANCED_BENCH 1@PID_SMALL_ENERGY_CELL 100@exp 250 script fix_boy@fix_Generic}
{56}{}{PID_MICRO_FUSION_CELL@Una unidad de producción de energía de tamaño mediano. Planta de fusión autónoma.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2&SK_SCIENCE 150@PID_REFINED_ORE 3&PID_ALLOYS 1&PID_ELECTRONIC_PARTS 1@PID_ADVANCED_BENCH 1@PID_MICRO_FUSION_CELL 100@exp 350 script fix_boy@fix_Generic}
{57}{}{PID_4_7MM_CASELESS@Munición. Calibre: 4.7 mm, sin casquillo.@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_GUNSMITH_B 2&SK_SCIENCE 175@PID_GUNPOWDER3 1&PID_METAL_PARTS2 1&PID_BLUEPRINT_4_7MM_CASELESS 1@PID_ADVANCED_BENCH 1@PID_4_7MM_CASELESS 100@exp 15000 script fix_boy@fix_Blueprint}
{58}{}{PID_2MM_EC_AMMO@Munición. Calibre: 2 mm, CE@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2&SK_SCIENCE 175@PID_GUNPOWDER3 1&PID_CYLINDRICAL_LOCK 1&PID_BLUEPRINT_2MM_EC_AMMO 1@PID_ADVANCED_BENCH 1@PID_2MM_EC_AMMO 100@exp 15000 script fix_boy@fix_Blueprint}
{59}{}{PID_9MM_MAUSER@Un Mauser M / 96, en Parabellum de 9x19 mm. En excelente condición. Extremadamente preciso. @@@PID_FIREWOOD 1&PID_METAL_PARTS 2&PID_PUMP_PARTS 3@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_9MM_MAUSER 1@exp 95 script fix_boy@fix_Generic}
{60}{}{PID_10MM_PISTOL@Una pistola de carga automática Colt 6520 de 10 mm. Cada vez que apriete el gatillo, se volverá a cargar automáticamente el arma de fuego hasta que el cargador esté vacío. Disparo único solamente, utilizando la potente ronda de 10 mm. @@@PID_FIREWOOD 1&PID_METAL_PARTS 5&PID_ALLOYS 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_10MM_PISTOL 1@exp 190 script fix_boy@fix_Generic}
{61}{}{PID_44_MAGNUM_REVOLVER@Siendo que esta es la pistola más poderosa del mundo, y puede volar tu cabeza, tienes que hacerte una pregunta. ¿Me siento afortunado? Bueno, ¿ya eres punk? @PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_FIREWOOD 1&PID_ALLOYS 2&PID_METAL_PARTS 5@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_44_MAGNUM_REVOLVER 1@exp 210 script fix_boy@fix_Generic}
{62}{}{PID_SPEED_LOADER@Lo útil para una recarga más rápida de un revólver.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_PUMP_PARTS 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SPEED_LOADER 1@exp 5 script fix_boy@fix_Generic}
{63}{}{PID_44_MAGNUM_SPEEDLOADER@Un .44 Magnum Revolver con un cargador veloz.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_44_MAGNUM_REVOLVER 1&PID_SPEED_LOADER 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_44_MAGNUM_SPEEDLOADER 1@exp 25 script fix_boy@fix_Generic}
{64}{}{PID_DESERT_EAGLE@Una antigua pistola Desert Eagle, con .44 Magnum. El interés por las películas de finales del siglo XX hizo de esta una de las pistolas más populares de todos los tiempos. @PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_FIREWOOD 1&PID_METAL_PARTS 3&PID_ALLOYS 3@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_DESERT_EAGLE 1@exp 170 script fix_boy@fix_Generic}
{65}{}{PID_EXTENDED_MAGAZINE@Una cargador extendido, para aquellos que no les gusta la recarga frecuente.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_PUMP_PARTS 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_EXTENDED_MAGAZINE 1@exp 5 script fix_boy@fix_Generic}
{66}{}{PID_DESERT_EAGLE_EXT_MAG@Una antigua pistola Desert Eagle, con .44 Magnum. El interés por las películas de finales del siglo XX hizo de esta una de las pistolas más populares de todos los tiempos. ¡Este ha sido equipado con un cargador ampliado para más diversión y juegos!@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_DESERT_EAGLE 1&PID_EXTENDED_MAGAZINE 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_DESERT_EAGLE_EXT_MAG 1@exp 30 script fix_boy@fix_Generic}
{67}{}{PID_NEEDLER_PISTOL@Sospecha que esta pistola de agujas Bringham alguna vez se usó para estudios de campo científicos. Utiliza pequeños dardos con forma de jeringa de plástico duro como munición. @PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_DOCTOR 2@PE_PROFESSION_GUNSMITH_S 2|PE_PROFESSION_DOCTOR 2@PID_FIREWOOD 1&PID_ALLOYS2 1&PID_ALLOYS 1&PID_METAL_PARTS 3&PID_METAL_PARTS2 1&PID_PUMP_PARTS 5&PID_BLUEPRINT_NEEDLER_PISTOL 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_NEEDLER_PISTOL 1@exp 600 script fix_boy@fix_Blueprint}
{68}{}{PID_14MM_PISTOL@Una pistola automática Sig-Sauer de 14 mm. Pistola grande de un solo disparo. Excelente artesanía. @PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_ALLOYS 3&PID_METAL_PARTS 3&PID_ALLOYS2 2&PID_BLUEPRINT_14MM_PISTOL 1@PID_ADVANCED_BENCH 1@PID_14MM_PISTOL 1@exp 500 script fix_boy@fix_Blueprint}
{69}{}{PID_223_PISTOL@Un rifle .223 modificado y acortado a una pistola. Esta es una arma de fuego única, obviamente hecha con amor y habilidad. @PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_HUNTING_RIFLE 1&PID_PUMP_PARTS 3&PID_ALLOYS2 1&PID_METAL_PARTS2 2&PID_BLUEPRINT_223_PISTOL 1@PID_ADVANCED_BENCH 1@PID_223_PISTOL 1@exp 800 script fix_boy@fix_Blueprint}
{70}{}{PID_PK12_GAUSS_PISTOL@Elogiada por su alcance y poder de frenado, la pistola Gauss PPK12 es de diseño alemán. La pistola utiliza un campo electromagnético para impulsar rondas a una velocidad tremenda y atravesar casi cualquier armadura.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_TECH_AUTO_TRIGGER 1&PID_TECH_MECH_ENGINE 2&PID_TECH_PLASMA 3&PID_ELECTRIC_AMPLIFIER 1&PID_BLUEPRINT_PK12_GAUSS_PISTOL 1@PID_MACHINERY_SMALL_GUNS 1@PID_PK12_GAUSS_PISTOL 1@exp 35000 script fix_boy@fix_Blueprint}
{71}{}{PID_GREASE_GUN@Este subfusil llenó los arsenales de la Guardia Nacional después de que el Ejército la reemplazó con armas más nuevas. Sin embargo, la "pistola de engrase" era simple y barata de fabricar, por lo que todavía hay algunas en uso.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_FIREWOOD 1&PID_METAL_PARTS 6@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_GREASE_GUN 1@exp 200 script fix_boy@fix_Generic}
{72}{}{PID_10MM_SMG@Subfusil ametrallador H&K MP9 (variante de 10 mm). Un SMG de tamaño mediano, capaz de disparo único y modo ráfaga.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_METAL_PARTS 2&PID_METAL_PARTS2 1&PID_ALLOYS 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_10MM_SMG 1@exp 400 script fix_boy@fix_Generic}
{73}{}{PID_HK_P90C@El Heckler & Koch P90c recién comenzaba a usarse en el momento de la guerra. El diseño bullpup del arma y su diseño compacto facilitan el control. El P90c duradero es apreciado por su confiabilidad y alta potencia de fuego en un paquete resistente y compacto.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_ALLOYS 3&PID_ALLOYS2 1&PID_METAL_PARTS 4&PID_METAL_PARTS2 2&PID_BLUEPRINT_P90 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_HK_P90C 1@exp 800 script fix_boy@fix_Blueprint}
{74}{}{PID_HK_G11@Esta pistola revolucionó el diseño de armas de asalto. El arma dispara un cartucho sin casquillo que consiste en un bloque de propulsor con una bala enterrada en su interior.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_TECH_DELINER 1&PID_TECH_ELE_ENGINE 1&PID_TECH_CONDEN 1&PID_ELECTRIC_AMPLIFIER 1&PID_BLUEPRINT_HK_G11 1@PID_MACHINERY_SMALL_GUNS 1@PID_HK_G11 1@exp 20000 script fix_boy@fix_Blueprint}
{75}{}{PID_HK_G11E@Esta pistola revolucionó el diseño del arma de apoyo a nivel de escuadrón. La pistola dispara un cartucho sin casquillo que consiste en un bloque de propulsor con una bala enterrada en su interior.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_HK_G11 1&PID_TECH_SCOPE 1&PID_TECH_MICROCHIPS 1&PID_BLUEPRINT_HK_G11E 1@PID_MACHINERY_SMALL_GUNS 1@PID_HK_G11E 1@exp 25000 script fix_boy@fix_Blueprint}
{76}{}{PID_RED_RYDER_BB_GUN@Un rifle Red Ryder BB. El clásico. @@@PID_FIREWOOD 1&PID_PUMP_PARTS 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_RED_RYDER_BB_GUN 1@exp 30 script fix_boy@fix_Generic}
{77}{}{PID_HUNTING_RIFLE@Un rifle semiautomático Colt Rangemaster, en calibre .223. Solo disparo único.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_FIREWOOD 1&PID_METAL_PARTS 4&PID_ALLOYS 3@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_HUNTING_RIFLE 1@exp 200 script fix_boy@fix_Generic}
{78}{}{PID_SCOPE@Un alcance óptico para todo clima en excelentes condiciones.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_METAL_PARTS 1&PID_PUMP_PARTS 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SCOPE 1@exp 40 script fix_boy@fix_Generic}
{79}{}{PID_SCOPED_HUNTING_RIFLE@Nada es mejor que ver esa mirada de sorpresa en la cara de tu objetivo. El Loophole x20 Scope en este rifle de caza lo hace más fácil que nunca. Preciso desde el primer disparo hasta el último, sin importar qué tipo de juego estés buscando.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_HUNTING_RIFLE 1&PID_SCOPE 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SCOPED_HUNTING_RIFLE 1@exp 105 script fix_boy@fix_Generic}
{80}{}{PID_SNIPER_RIFLE@Un rifle de francotirador DKS-501. Excelente arma de proyectil de largo alcance. Originalmente .308, pero este se ajusto al calibre .223, que es más común.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_ALLOYS2 1&PID_ALLOYS 3&PID_METAL_PARTS 6&PID_METAL_PARTS2 3&PID_SCOPE 1&PID_BLUEPRINT_SNIPER_RIFLE 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_SNIPER_RIFLE 1@exp 1200 script fix_boy@fix_Blueprint}
{81}{}{PID_M72_GAUSS_RIFLE@El rifle M72 es de diseño alemán. Utiliza un campo electromagnético para impulsar balas a una velocidad tremenda ... y atravesar casi cualquier obstáculo. Su alcance, precisión y potencia de frenado son casi incomparables.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_CARBON_POLYMER 1&PID_TECH_AUTO_TRIGGER 2&PID_TECH_CONDEN 1&PID_TECH_TRANSFORMATOR 2&PID_ABSORBER 1&PID_TECH_ELE_ENGINE 2&PID_BLUEPRINT_M72_GAUSS_RIFLE 1@PID_MACHINERY_SMALL_GUNS 1@PID_M72_GAUSS_RIFLE 1@exp 50000 script fix_boy@fix_Blueprint}
{82}{}{PID_TOMMY_GUN@Esta ametralladora Thompson M1928 es un arma de aspecto siniestro; Cada vez que lo sostienes, tienes ganas de ponerte un sombrero de fieltro y crujir los nudillos. El Thompson está bien alimentado por un gran cargador de tambores de 75 balas.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_FIREWOOD 1&PID_METAL_PARTS 3&PID_PUMP_PARTS 7@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_TOMMY_GUN 1@exp 145 script fix_boy@fix_Generic}
{83}{}{PID_ASSAULT_RIFLE@Un fusil de asalto AK-112 de 5 mm. Un viejo modelo militar, fuera de uso en la época de la guerra. Puede disparar un solo disparo o rafaga, utilizando las municiones de alta velocidad de 5 mm.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_ALLOYS 4&PID_ALLOYS2 2&PID_METAL_PARTS 1&PID_METAL_PARTS2 1&PID_BLUEPRINT_ASSAULT_RIFLE 1@PID_ADVANCED_BENCH 1@PID_ASSAULT_RIFLE 1@exp 750 script fix_boy@fix_Blueprint}
{84}{}{PID_ASSAULT_RIFLE_EXT_MAG@Este rifle de asalto tiene un cargador de munición extendido de tamaño militar. La capacidad ampliada de la revista lo hace más divertido que nunca para Rociar-y-Rezar.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_ASSAULT_RIFLE 1&PID_EXTENDED_MAGAZINE 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_ASSAULT_RIFLE_EXT_MAG 1@exp 200 script fix_boy@fix_Generic}
{85}{}{PID_FN_FAL@Este rifle ha sido utilizado más ampliamente por las fuerzas armadas que cualquier otro rifle en la historia. Es un arma de asalto confiable para cualquier terreno o situación táctica.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_METAL_PARTS 2&PID_ALLOYS 3&PID_ALLOYS2 2&PID_BLUEPRINT_FN_FAL 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_FN_FAL 1@exp 500 script fix_boy@fix_Blueprint}
{86}{}{PID_FN_FAL_HPFA@La variante FN FAL HPFA. Este modelo ha sido modificado para aumentar su potencia de fuego haciendo que el arma sea mucho más peligrosa, tanto para el usuario como para su objetivo.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FN_FAL 1&PID_FIREWOOD 1&PID_ALLOYS 3&PID_METAL_PARTS2 2&PID_ALLOYS2 2@PID_ADVANCED_BENCH 1@PID_FN_FAL_HPFA 1@exp 1100 script fix_boy@fix_Generic}
{87}{}{PID_FN_FAL_NIGHT_SCOPE@Este rifle ha sido utilizado más ampliamente por las fuerzas armadas que cualquier otro rifle en la historia. Es un arma de asalto confiable para cualquier terreno o situación táctica. Esta arma ha sido equipada con una mira nocturna para una mayor precisión nocturna.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2&SK_SCIENCE 200&SK_REPAIR 175@PID_FN_FAL_HPFA 1&PID_SCOPE 1&PID_ALLOYS2 5&PID_BLUEPRINT_FN_FAL_NIGHT_SCOPE 1@PID_MACHINERY_SMALL_GUNS 1@PID_FN_FAL_NIGHT_SCOPE 1@exp 1300 script fix_boy@fix_Blueprint}
{88}{}{PID_INDEPENDENT@This was an experimental weapon at the time of the war. Manufactured, primarily, from high-strength polymers, the weapon is almost indestructible. It's light, fast firing, accurate, and can be broken down without the use of any tools.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_METAL_PARTS2 2&PID_ALLOYS2 2&PID_ALLOYS 3&PID_METAL_PARTS 4&PID_BLUEPRINT_INDEPENDENT 1@PID_ADVANCED_BENCH 1@PID_INDEPENDENT 1@exp 1200 script fix_boy@fix_Blueprint}
{89}{}{PID_SHOTGUN@Una escopeta Winchester Widowmaker de doble cañón de calibre 12. cañon corto, con empuñadura de caoba.@@@PID_FIREWOOD 1&PID_METAL_PARTS 5@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SHOTGUN 1@exp 170 script fix_boy@fix_Generic}
{90}{}{PID_SAWED_OFF_SHOTGUN@Alguien se tomó el tiempo para cortar los últimos centímetros del cañón y el stock de esta escopeta. Ahora, la amplia difusión de los disparos de cañón corto de este cañón de mano lo hace perfecto para el control de multitudes de corto alcance.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_SHOTGUN 1&PID_METAL_PARTS 1&PID_PUMP_PARTS 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SAWED_OFF_SHOTGUN 1@exp 100 script fix_boy@fix_Generic}
{91}{}{PID_COMBAT_SHOTGUN@Una escopeta de combate Winchester City-Killer de calibre 12, variante bullpup. En excelentes condiciones, tiene la modificación opcional del sellador ambiental DesertWarfare para mayor confiabilidad.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_FIREWOOD 1&PID_METAL_PARTS 6&PID_ALLOYS 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_COMBAT_SHOTGUN 1@exp 220 script fix_boy@fix_Generic}
{92}{}{PID_HK_CAWS@La CAWS, abreviatura de Sistema de armas de asalto cercano, es una herramienta útil para el combate a corta distancia. El diseño bullpup le da al arma una longitud corta y fácil de manejar, al tiempo que conserva la longitud suficiente del cañón para sus proyectiles de alta velocidad.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_ALLOYS2 2&PID_ALLOYS 2&PID_METAL_PARTS 3&PID_PUMP_PARTS 3&PID_BLUEPRINT_HK_CAWS 1@PID_ADVANCED_BENCH 1@PID_HK_CAWS 1@exp 500 script fix_boy@fix_Blueprint}
{93}{}{PID_PANCOR_JACKHAMMER@El Jackhammer, a pesar de su nombre, es una escopeta fácil de controlar, incluso cuando se dispara con la automática completa. El popular diseño bullpup, que coloca la revista detrás del gatillo, hace que el arma esté bien equilibrada y sea fácil de controlar.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_FIREWOOD 1&PID_METAL_PARTS 2&PID_METAL_PARTS2 2&PID_ALLOYS 3&PID_ALLOYS2 1&PID_BLUEPRINT_PANCOR_JACKHAMMER 1@PID_ADVANCED_BENCH 1@PID_PANCOR_JACKHAMMER 1@exp 800 script fix_boy@fix_Blueprint}
{94}{}{PID_SAIGA12@Imagine un AK-47 limitado a fuego semiautomático con una cámara reconstruida para albergar cartuchos de escopeta y usted tiene esta escopeta automática. Extremadamente potente a corto alcance, pierde precisión a largo alcance.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_TECH_DELINER 1&PID_TECH_GUN_CONTROL 2&PID_TECH_MICROCHIPS 1&PID_ARM_CARBON 3&PID_BLUEPRINT_SAIGA_12 1@PID_MACHINERY_SMALL_GUNS 1@PID_SAIGA12 1@exp 25000 script fix_boy@fix_Blueprint}
{95}{}{PID_GRENADE_PISTOL@Diseñado mucho antes de la gran guerra, el lanzagranadas de pistola Fabrique Nationale 69A1 se convirtió en el sistema de apoyo de fuego portátil estándar de las unidades de la policía militar de EE. UU. Estacionadas en Canadá durante el conflicto.@PE_PROFESSION_GUNSMITH_S 1@PE_PROFESSION_GUNSMITH_S 1@PID_ALLOYS 5&PID_METAL_PARTS 2&PID_FIREWOOD 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_GRENADE_PISTOL 1@exp 180 script fix_boy@fix_Generic}
{96}{}{PID_GRENADE_LAUNCHER@Un lanzagranadas de dos disparos.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_ALLOYS 5&PID_FIREWOOD 1&PID_ALLOYS2 1&PID_METAL_PARTS2 2@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_GRENADE_LAUNCHER 1@exp 800 script fix_boy@fix_Generic}
{97}{}{PID_M16@Rifle automático con poder estadounidense, con municiones de 5 mm.@PE_PROFESSION_GUNSMITH_S 2@PE_PROFESSION_GUNSMITH_S 2@PID_ALLOYS 3&PID_FIREWOOD 1&PID_ALLOYS2 2&PID_METAL_PARTS2 2&PID_BLUEPRINT_M16 1@PID_ADVANCED_BENCH 1@PID_M16 1@exp 1000 script fix_boy@fix_Generic}
{98}{}{PID_FLAMER@Un lanzallamas modelo Flambe 450, variación varminter. Dispara una pequeña pulverización de líquido inflamable y extremadamente caliente. Requiere combustible especializado para funcionar correctamente.@@@PID_FIREWOOD 1&PID_ALLOYS 3@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_FLAMER 1@exp 150 script fix_boy@fix_Generic}
{99}{}{PID_HEATERCHAMBER@Enables the use of extremely heated fuel with the flamethrower.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2&SK_REPAIR 100@PID_METAL_PARTS2 1&PID_ALLOYS2 1@PID_ADVANCED_BENCH 1@PID_HEATERCHAMBER 1@exp 400 script fix_boy@fix_Generic}
{100}{}{PID_IMPROVED_FLAMETHROWER@Un lanzallamas modelo Flambe 450, variación varmiter. Dispara una pequeña pulverización de líquido inflamable y extremadamente caliente. Requiere combustible especializado para funcionar correctamente. Este modelo ha sido modificado para disparar una mezcla más caliente que causa mayor combustibilidad y daño.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_FLAMER 1&PID_HEATERCHAMBER 1&PID_BLUEPRINT_IMPROVED_FLAMETHROWER 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_IMPROVED_FLAMETHROWER 1@exp 200 script fix_boy@fix_Blueprint}
{101}{}{PID_ROCKET_LAUNCHER@Un lanzacohetes Rockwell BigBazooka. Con el gatillo de lujo de 3 lb. Dispara AP o Cohetes Explosivos.@PE_PROFESSION_GUNSMITH_B 1@PE_PROFESSION_GUNSMITH_B 1@PID_ALLOYS2 2&PID_ALLOYS 5&PID_METAL_PARTS 2&PID_METAL_PARTS2 1&PID_BLUEPRINT_ROCKET_LAUNCHER 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_ROCKET_LAUNCHER 1@exp 750 script fix_boy@fix_Blueprint}
{102}{}{PID_EL_ROCKET_LAUNCHER@Esta arma está diseñada para lanzar cohetes que emiten un fuerte impulso eléctrico al impactar efectivamente electrocutando a cualquiera en su radio de explosión.@PE_PROFESSION_GUNSMITH_B 1@PE_PROFESSION_GUNSMITH_B 1@PID_ALLOYS2 2&PID_ELECTRONIC_PARTS 5&PID_METAL_PARTS 2&PID_METAL_PARTS2 1&PID_BLUEPRINT_EL_ROCKET_LAUNCHER 1@PID_ADVANCED_BENCH 1@PID_EL_ROCKET_LAUNCHER 1@exp 850 script fix_boy@fix_Blueprint}
{103}{}{PID_M203@Lanzacohetes de cuatro barriles que puede cargar problemas estándar para cohetes explosivos / AP, así como cohetes incendiarios.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_TECH_GUN_CONTROL 4&PID_TECH_SEMI_TRIGGER 1&PID_TECH_MECH_ENGINE 3&PID_BLUEPRINT_M203 1@PID_MACHINERY_SMALL_GUNS 1@PID_M203 1@exp 75000 script fix_boy@fix_Blueprint}
{104}{}{PID_M60@Esta ametralladora relativamente ligera fue apreciada por los militares de todo el mundo por su alta cadencia de fuego. Este diseño confiable, probado en el campo de batalla, se utilizó en vehículos y para apoyo de fuego a nivel de escuadrón.@PE_PROFESSION_GUNSMITH_B 1@PE_PROFESSION_GUNSMITH_B 1@PID_METAL_PARTS 7&PID_ALLOYS 7@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_M60 1@exp 350 script fix_boy@fix_Generic}
{105}{}{PID_LIGHT_SUPPORT_WEAPON@Esta arma de apoyo a nivel de escuadrón tiene un diseño bullpup. El diseño bullpup hace que sea difícil de usar mientras está acostado. Debido a esto, fue enviado a las unidades de la Guardia Nacional. Sin embargo, se ganó una reputación como un arma confiable que tiene mucho impacto para su tamaño.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_ALLOYS2 2&PID_METAL_PARTS 1&PID_METAL_PARTS2 1&PID_ALLOYS 5&PID_PUMP_PARTS 5&PID_BLUEPRINT_LIGHT_SUPPORT_WEAPON 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_LIGHT_SUPPORT_WEAPON 1@exp 800 script fix_boy@fix_Blueprint}
{106}{}{PID_BOZAR@El último refinamiento del arte del francotirador. Aunque, algo quisquilloso y propenso a atascarse si no se mantiene escrupulosamente limpio, la precisión del arma grande compensa con creces sus requisitos de mantenimiento adicionales.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_CARBON_POLYMER 1&PID_TECH_SCOPE 1&PID_TECH_MICROCHIPS 6&PID_TECH_GUN_CONTROL 3&PID_BLUEPRINT_BOZAR 1@PID_MACHINERY_SMALL_GUNS 1@PID_BOZAR 1@exp 50000 script fix_boy@fix_Blueprint}
{107}{}{PID_MINIGUN@Una ametralladora personal Rockwell CZ53. Una ametralladora de múltiples cañones disparando municiones de 5 mm a más de 60,000 RPM.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_FIREWOOD 1&PID_PUMP_PARTS 7&PID_ALLOYS 5&PID_ALLOYS2 2&PID_METAL_PARTS2 2&PID_METAL_PARTS 2@PID_MULTI_TOOL 1&PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_MINIGUN 1@exp 1000 script fix_boy@fix_Blueprint}
{108}{}{PID_AVENGER_MINIGUN@Rockwell diseñó a la" Vengadora" como el reemplazo de su antigua ametralladora personal CZ53. Las mejoras de diseño de la "Vengadora" incluyen perforaciones de barril cromadas, aletas de gel, enfriamiento y cromo mejoradas. Esto le da un mayor alcance y letalidad.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_MINIGUN 1&PID_METAL_PARTS2 3&PID_ALLOYS2 2&PID_BLUEPRINT_AVENGER_MINIGUN 1@PID_MULTI_TOOL 1&PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_AVENGER_MINIGUN 1@exp 1200 script fix_boy@fix_Blueprint}
{109}{}{PID_VINDICATOR_MINIGUN@El Vindicator arroja más de 90,000 balas sin casquillos por minuto en sus seis barriles de polímero de carbono. Como el pináculo de la habilidad de ingeniería teutónica, es el arma de mano definitiva.@PE_PROFESSION_GUNSMITH_B 2@PE_PROFESSION_GUNSMITH_B 2@PID_ABSORBER 2&PID_ROTARY_CHAMBER 1&PID_TECH_DELINER 2&PID_ARM_CARBON 4&PID_BLUEPRINT_VINDICATOR_MINIGUN 1@PID_MACHINERY_SMALL_GUNS 1@PID_VINDICATOR_MINIGUN 1@exp 30000 script fix_boy@fix_Blueprint}
{110}{}{PID_LASER_PISTOL@Una pistola láser Wattz 1000. Modelo civil, por lo que la potencia es menor que las versiones militares o policiales. Utiliza pequeñas células de energía.@@SK_REPAIR 50@PID_FIREWOOD 1&PID_ALLOYS 2&PID_ELECTRONIC_PARTS 2&PID_METAL_PARTS 4@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_LASER_PISTOL 1@exp 280 script fix_boy@fix_Generic}
{111}{}{PID_MFT_SYSTEM@Sistema mejorado de orientación de armas láser, utilizando un campo magnético.@PE_PROFESSION_ENERGY_EXPERT 1@PE_PROFESSION_ENERGY_EXPERT 1&SK_REPAIR 100@PID_METAL_PARTS 1&PID_ELECTRONIC_PARTS 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_MFT_SYSTEM 1@exp 80 script fix_boy@fix_Generic}
{112}{}{PID_MAGNETO_LASER_PISTOL@Esta pistola láser Wattz 1000 se ha actualizado con un sistema de orientación de campo magnético que aprieta la emisión del láser, lo que le da a esta pistola un poder de penetración adicional.@PE_PROFESSION_ENERGY_EXPERT 1@PE_PROFESSION_ENERGY_EXPERT 1@PID_LASER_PISTOL 1&PID_METAL_PARTS 2&PID_FIREWOOD 1&PID_ALLOYS 4&PID_ELECTRONIC_PARTS 3&PID_MFT_SYSTEM 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_MAGNETO_LASER_PISTOL 1@exp 350 script fix_boy@fix_Generic}
{113}{}{PID_PLASMA_PISTOL@Pistola de plasma Glock 86. Diseñado por el Gaston Glock AI. Dispara un pequeño rayo de plasma sobrecalentado. Alimentado por una pequeña celda de energía.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_ELECTRONIC_PARTS 1&PID_FIREWOOD 1&PID_ALLOYS 4&PID_ALLOYS2 1&PID_METAL_PARTS2 1&PID_BLUEPRINT_PLASMA_PISTOL 1@PID_ADVANCED_BENCH 1@PID_PLASMA_PISTOL 1@exp 650 script fix_boy@fix_Blueprint}
{114}{}{PID_EXT_CAPACITOR_BATTERY@Almacenamiento de energía con capacidad adicional.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_METAL_PARTS2 1@PID_ADVANCED_BENCH 1@PID_EXT_CAPACITOR_BATTERY 1@exp 300 script fix_boy@fix_Generic}
{115}{}{PID_PLASMA_PISTOL_EXT_CAP@Esta pistola de plasma Glock 86 tiene su cámara de carcasa magnética realineada para reducir el drenaje de su celda de energía. Su eficiencia se ha duplicado, lo que le permite disparar más disparos antes de que se agote la batería.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_PLASMA_PISTOL 1&PID_EXT_CAPACITOR_BATTERY 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_PLASMA_PISTOL_EXT_CART 1@exp 50 script fix_boy@fix_Generic}
{116}{}{PID_YK32_PULSE_PISTOL@El YK32 nunca fue considerado un arma práctica debido a su uso ineficiente de energía y diseño voluminoso.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2&SK_SCIENCE 200&SK_REPAIR 175@PID_METAL_PARTS2 3&PID_ELECTRONIC_PARTS 3&PID_PUMP_PARTS 2&PID_ALLOYS 2&PID_BLUEPRINT_YK32_PULSE_PISTOL 1@PID_ADVANCED_BENCH 1@PID_YK32_PULSE_PISTOL 1@exp 1100 script fix_boy@fix_Blueprint}
{117}{}{PID_LASER_RIFLE@Un rifle láser Wattz 2000. Utiliza células de micro fusión para láseres más potentes y un cañón extendido para un alcance adicional.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_FIREWOOD 1&PID_ALLOYS2 2&PID_METAL_PARTS 2&PID_ALLOYS 4&PID_ELECTRONIC_PARTS 3&PID_BLUEPRINT_LASER_RIFLE 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_LASER_RIFLE 1@exp 700 script fix_boy@fix_Blueprint}
{118}{}{PID_LASER_RIFLE_EXT_CAP@Este rifle láser Wattz 2000 ha mejorado su sistema de recarga y ha instalado un chip de reciclaje especial que reduce el drenaje en las celulas de micro fusión en un 50%.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_LASER_RIFLE 1&PID_EXT_CAPACITOR_BATTERY 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_LASER_RIFLE_EXT_CAP 1@exp 50 script fix_boy@fix_Generic}
{119}{}{PID_PLASMA_RIFLE@Un rifle de plasma Winchester modelo P94. Un arma de energía de grado industrial, disparando rayos de plasma sobrecalentados por un cañón superconductor. Alimentado por celulas de micro fusion.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_FIREWOOD 1&PID_METAL_PARTS2 2&PID_ALLOYS2 2&PID_ALLOYS 6&PID_ELECTRONIC_PARTS 5&PID_BLUEPRINT_PLASMA_RIFLE 1@PID_ADVANCED_BENCH 1|PID_MACHINERY_SMALL_GUNS 1@PID_PLASMA_RIFLE 1@exp 1000 script fix_boy@fix_Blueprint}
{120}{}{PID_TURBO_PLASMA_RIFLE@Un rifle de plasma Winchester P94 modificado. La cámara del perno de plasma se ha conectado para acelerar el proceso de formación del disparo.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_PLASMA_RIFLE 1&PID_ELECTROMAGNETIC 1&PID_PLASMA_PARTS 1&PID_TECH_TRANSFORMATOR 5&PID_TECH_ELE_WIRES 2&PID_BLUEPRINT_TURBO_PLASMA_RIFLE 1@PID_MACHINERY_SMALL_GUNS 1@PID_TURBO_PLASMA_RIFLE 1@exp 30000 script fix_boy@fix_Blueprint}
{121}{}{PID_YK42B_PULSE_RIFLE@El YK42B es un arma de pulso eléctrico desarrollada por el Consorcio de Energía Yuma Flats. Se considera un arma muy superior a la pistola YK32, que tiene una mayor capacidad de carga y alcance.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_ELECTROMAGNETIC 1&PID_PLASMA_ACCELERATOR 1&PID_TECH_CONDEN 3&PID_TECH_TRANSFORMATOR 1&PID_TECH_ELE_WIRES 3&PID_TECH_PLASMA 1&PID_BLUEPRINT_YK42B_PULSE_RIFLE 1@PID_MACHINERY_SMALL_GUNS 1@PID_YK42B_PULSE_RIFLE 1@exp 50000 script fix_boy@fix_Blueprint}
{122}{}{PID_SOLAR_SCORCHER@Sin los rayos del sol para cargar los condensadores de esta arma, esta pistola no puede encender una cerilla. Sin embargo, a plena luz del día, las células fotoeléctricas experimentales que alimentan al arma le permiten convertir casi cualquier cosa en una criatura asada.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2&SK_SCIENCE 175@PID_METAL_PARTS2 4&PID_ALLOYS2 3&PID_PUMP_PARTS 5&PID_BLUEPRINT_SOLAR_SCORCHER 1@PID_ADVANCED_BENCH 1@PID_SOLAR_SCORCHER 1@exp 1200 script fix_boy@fix_Blueprint}
{123}{}{PID_GATLING_LASER@Un láser H&K L30 Gatling. Diseñados específicamente para uso militar, estos estaban en la etapa de prototipo al comienzo de la guerra. Los barriles múltiples permiten disparar más tiempo antes de sobrecalentar. Alimentado por celulas de micro fusion.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2&SK_SCIENCE 130@PID_MINIGUN 1&PID_ALLOYS2 3&PID_METAL_PARTS2 5&PID_ELECTRONIC_PARTS 3&PID_BLUEPRINT_GATLING_LASER 1@PID_ADVANCED_BENCH 1@PID_GATLING_LASER 1@exp 1600 script fix_boy@fix_Blueprint}
{124}{}{PID_BRASS_KNUCKLES@Empuñadura de nudillos endurecida que en realidad está hecha de acero. Protegen tu mano y hacen más daño en un combate desarmado.@@@PID_PUMP_PARTS 4@@PID_BRASS_KNUCKLES 1@exp 20 script fix_boy@fix_Generic}
{125}{}{PID_SPIKED_KNUCKLES@Una versión mejorada de los clásicos nudillos. Los nudillos con pinchos hacen más daño, desgarrando la carne de tu oponente en un combate desarmado.@@@PID_METAL_PARTS 3@@PID_SPIKED_KNUCKLES 1@exp 90 script fix_boy@fix_Generic}
{126}{}{PID_POWER_FIST@Un "Big Frigger" Servopuño de BeatCo. Considerado por muchos como el arma definitiva para usar en combate desarmado. Otros simplemente están asustados. Alimentado por pequeñas células de energía.@PE_PROFESSION_ENERGY_EXPERT 1@PE_PROFESSION_ENERGY_EXPERT 1@PID_ALLOYS 3&PID_ELECTRONIC_PARTS 4@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_POWER_FIST 1@exp 260 script fix_boy@fix_Generic}
{127}{}{PID_POWER_SERVOS@Un sistema para modificar el Servopuño.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_ALLOYS2 1&PID_METAL_PARTS2 1@PID_ADVANCED_BENCH 1@PID_POWER_SERVOS 1@exp 500 script fix_boy@fix_Generic}
{128}{}{PID_MEGA_POWER_FIST@Un "Big Frigger" Servopuño de BeatCo. Considerado por muchos como el arma definitiva para usar en combate desarmado. Este ha mejorado los servos de potencia para aumentar la fuerza. Alimentado por pequeñas células de energía.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_POWER_FIST 1&PID_POWER_SERVOS 1&PID_BLUEPRINT_MEGA_POWER_FIST 1@PID_ADVANCED_BENCH 1@PID_MEGA_POWER_FIST 1@exp 100 script fix_boy@fix_Blueprint}
{129}{}{PID_SHARPENED_POLE@Un palo de madera afilado en un extremo.@@@PID_FIREWOOD 1@@PID_SHARPENED_POLE 1@exp 5 script fix_boy@fix_Generic}
{130}{}{PID_SPEAR@Un arma cortante y punzante de hoja afilada.@@@PID_PUMP_PARTS 4&PID_SHARPENED_POLE 1&PID_METAL_PARTS 1@@PID_SPEAR 2@exp 50 script fix_boy@fix_Generic}
{131}{}{PID_SHARP_SPEAR@Un arma de asta con punta de afeitar. El eje es de madera y la punta es de acero afilado.@@@PID_SPEAR 1&PID_FLINT 1&PID_METAL_PARTS 3@@PID_SHARP_SPEAR 1@exp 100 script fix_boy@fix_Generic}
{132}{}{PID_KNIFE@Un arma cortante y punzante de hoja afilada.@@@PID_PUMP_PARTS 2&PID_FIREWOOD 1&PID_METAL_PARTS 1@@PID_KNIFE 2@exp 60 script fix_boy@fix_Generic}
{133}{}{PID_COMBAT_KNIFE@Un cuchillo de combate de alta calidad, el Stallona es de SharpWit, Inc. ¡El filo de esta hoja está garantizado para más de una década de uso!@@@PID_METAL_PARTS 3&PID_FLINT 1&PID_FIREWOOD 1&PID_PUMP_PARTS 4@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_COMBAT_KNIFE 1@exp 135 script fix_boy@fix_Generic}
{134}{}{PID_RIPPER@Una espada vibradora Ripper (tm). Impulsado por pequeñas células de energía, la cadena afilada rasga y rasga en su objetivo.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_ALLOYS2 1&PID_ALLOYS 2&PID_ELECTRONIC_PARTS 1&PID_BLUEPRINT_RIPPER 1@PID_ADVANCED_BENCH 1@PID_RIPPER 1@exp 300 script fix_boy@fix_Blueprint}
{135}{}{PID_SLEDGEHAMMER@Una gran almadena con gran mango. Muy popular entre la multitud muscular.@@@PID_FIREWOOD 1&PID_METAL_PARTS 1@@PID_SLEDGEHAMMER 1@exp 50 script fix_boy@fix_Generic}
{136}{}{PID_SUPER_SLEDGE@Una Súper Almadena, fabricado por la Hermandad del Acero, utilizando la mejor tecnología de armas disponible. Incluye un dispositivo de almacenamiento de energía cinética, para aumentar el retroceso.@@@PID_METAL_PARTS2 2&PID_ALLOYS 1&PID_ELECTRONIC_PARTS 1&PID_SLEDGEHAMMER 1&PID_BLUEPRINT_SUPER_SLEDGE 1@PID_ADVANCED_BENCH 1@PID_SUPER_SLEDGE 1@exp 500 script fix_boy@fix_Blueprint}
{137}{}{PID_CATTLE_PROD@El mejor amigo de un granjero de Wattz Electronics. Utiliza pequeñas células de energía para obtener energía.@PE_PROFESSION_ENERGY_EXPERT 1@PE_PROFESSION_ENERGY_EXPERT 1@PID_FIREWOOD 1&PID_ELECTRONIC_PARTS 4&PID_ALLOYS 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_CATTLE_PROD 1@exp 250 script fix_boy@fix_Generic}
{138}{}{PID_IMP_CAPACITOR_BATTERY@Versión mejorada de almacenamiento electrico, permite una mayor descarga.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_ALLOYS2 1&PID_ELECTRONIC_PARTS 3&PID_METAL_PARTS2 1&PID_METAL_PARTS 2&PID_ALLOYS 1@PID_ADVANCED_BENCH 1@PID_IMP_CAPACITOR_BATTERY 1@exp 700 script fix_boy@fix_Generic}
{139}{}{PID_SUPER_CATTLE_PROD@El mejor amigo de un granjero de Wattz Electronics. Este modelo se ha actualizado para aumentar la descarga eléctrica.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_CATTLE_PROD 1&PID_IMP_CAPACITOR_BATTERY 1&PID_BLUEPRINT_SUPER_CATTLE_PROD 1@PID_ADVANCED_BENCH 1@PID_SUPER_CATTLE_PROD 1@exp 150 script fix_boy@fix_Blueprint}
{140}{}{PID_THROWING_KNIFE@Un cuchillo, equilibrado específicamente para lanzar. Hecho de titanio y afilado con láser.@@@PID_METAL_PARTS 4&PID_FIREWOOD 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_THROWING_KNIFE 10@exp 160 script fix_boy@fix_Generic}
{141}{}{PID_MOLOTOV_COCKTAIL@Una granada inflamable casera.@@@PID_ROT_GUT 16&PID_ROPE 1&PID_ADV_SUPERBURN 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_MOLOTOV_COCKTAIL 4@exp 320 script fix_boy@fix_Generic}
{142}{}{PID_FRAG_GRENADE@Una granada de fragmentación genérica. Contiene una pequeña cantidad de altos explosivos, el contenedor en sí forma la mayoría de los fragmentos dañinos. Explota al contacto.@PE_PROFESSION_DEMOLITION_EXPERT 1@PE_PROFESSION_DEMOLITION_EXPERT 1@PID_METAL_PARTS 1&PID_GUNPOWDER 4@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_FRAG_GRENADE 10@exp 100 script fix_boy@fix_Generic}
{143}{}{PID_PLASMA_GRENADE@Una unidad de suministro de plasma sellada magnéticamente, con explosivos detonantes. Crea una explosión de plasma sobrecalentado al contacto.@PE_PROFESSION_DEMOLITION_EXPERT 2@PE_PROFESSION_DEMOLITION_EXPERT 2@PID_METAL_PARTS 1&PID_REFINED_ORE 2&PID_BLUEPRINT_PLASMA_GRENADE 1@PID_ADVANCED_BENCH 1@PID_PLASMA_GRENADE 10@exp 200 script fix_boy@fix_Blueprint}
{144}{}{PID_DYNACORD@Esta mezcla letal de Dinamita y Cordex combina lo mejor de ambos, dejándote sin otra opción que adorarlo.@PE_PROFESSION_DEMOLITION_EXPERT 2@PE_PROFESSION_DEMOLITION_EXPERT 2@PID_METAL_PARTS2 1&PID_GUNPOWDER2 8@PID_ADVANCED_BENCH 1@PID_DYNACORD 10@exp 400 script fix_boy@fix_Generic}
{145}{}{PID_PULSE_GRENADE@No afecta a las criaturas biológicas. Contacto fuze.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2&SK_SCIENCE 175&SK_REPAIR 150@PID_METAL_PARTS 3&PID_ALLOYS 6&PID_METAL_PARTS2 5&PID_ALLOYS2 1&PID_ELECTRONIC_PARTS2 3&PID_TECH_CONDEN 3&PID_TECH_ELE_WIRES 2&PID_BLUEPRINT_PULSE_GRENADE 1@PID_MACHINERY_ENERGY_CELLS 1@PID_PULSE_GRENADE 10@exp 200 script fix_boy@fix_Blueprint}
{146}{}{PID_SHOCK_GRENADE@Esta granada emite un fuerte impulso eléctrico electrocutando efectivamente a cualquiera en su radio de explosión.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2&SK_SCIENCE 135@PID_METAL_PARTS 2&PID_ALLOYS 2&PID_METAL_PARTS2 1&PID_ALLOYS2 1&PID_ELECTRONIC_PARTS 2&PID_BLUEPRINT_SHOCK_GRENADE 1@PID_ADVANCED_BENCH 1@PID_SHOCK_GRENADE 10@exp 700 script fix_boy@fix_Blueprint}
{147}{}{PID_DYNAMITE@Un alto explosivo, que consiste en nitroglicerina mezclada con la sustancia absorbente kiselguhr. Incluye un temporizador.@PE_PROFESSION_DEMOLITION_EXPERT 2@PE_PROFESSION_DEMOLITION_EXPERT 2@PID_GUNPOWDER2 6&PID_DETONATOR_PARTS 1&PID_BLUEPRINT_DYNAMITE 1@PID_ADVANCED_BENCH 1@PID_DYNAMITE 1@exp 330 script fix_boy@fix_Blueprint}
{148}{}{PID_PLASTIC_EXPLOSIVES@Un trozo de Cordex, una marca militar de explosivos plásticos. Altamente estable, muy destructivo. Incluye un detonador.@PE_PROFESSION_DEMOLITION_EXPERT 2@PE_PROFESSION_DEMOLITION_EXPERT 2@PID_GUNPOWDER2 12&PID_DETONATOR_PARTS 1&PID_BLUEPRINT_PLASTIC_EXPLOSIVES 1@PID_ADVANCED_BENCH 1@PID_PLASTIC_EXPLOSIVES 1@exp 450 script fix_boy@fix_Blueprint}
{149}{}{PID_ANTIDOTE@Una botella que contiene un antídoto casero para el veneno. Un líquido lechoso con trozos flotantes de carne de escorpión.@PE_PROFESSION_DOCTOR 1@PE_PROFESSION_DOCTOR 1@PID_SCORPION_TAIL 5@@PID_ANTIDOTE 1@exp 150 script fix_boy@fix_Generic}
{150}{}{PID_JET_ANTIDOTE@Este antídoto cura los efectos de las drogas.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_SCIENCE 165@PID_CHEMICALS2 3&PID_BIOGEL_ADV_NEW 2&PID_ANTIDOTE 2&PID_JET 2&PID_BLUEPRINT_JET_ANTIDOTE 1@PID_MED_MACHINE 1@PID_JET_ANTIDOTE 1@exp 1000 script fix_boy@fix_Blueprint}
{151}{}{PID_WEAK_HEALING_POWDER@Un agente curativo débil de baja tecnología. No es realmente un estímulo, pero servirá.@@@PID_XANDER_ROOT 1@@PID_WEAK_HEALING_POWDER 1@exp 10 script fix_boy@fix_Generic}
{152}{}{PID_HEALING_POWDER@Un polvo curativo de baja tecnología. No es realmente un estímulo, pero servirá.@@@PID_XANDER_ROOT 1&PID_BROC_FLOWER 1@@PID_HEALING_POWDER 1@exp 20 script fix_boy@fix_Generic}
{153}{}{PID_STIMPAK@Un químico curativo. Cuando se inyecta, el químico proporciona la curación inmediata de heridas menores.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 100@PID_HYPODERMIC_NEEDLE 1&PID_BIO_GEL 1&PID_XANDER_ROOT 1&PID_BROC_FLOWER 1&PID_BLUEPRINT_STIMPAK 1@PID_ADVANCED_BENCH 1|PID_MED_MACHINE 1@PID_STIMPAK 1@exp 110 script fix_boy@fix_Blueprint}
{154}{}{PID_SUPER_STIMPAK@Un químico curativo avanzado. Muy poderoso en terminos curativos.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 140@PID_STIMPAK 1&PID_BIO_GEL 2&PID_CHEMICALS 1&PID_BLUEPRINT_SUPER_STIMPAK 1@PID_MED_MACHINE 1@PID_SUPER_STIMPAK 1@exp 220 script fix_boy@fix_Blueprint}
{155}{}{PID_HYPO@Un instrumento de inyección médica de algún tipo. Se ve muy de alta tecnología. No sabe con qué está lleno, pero parece que es extremadamente curativo. Genial.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2@PID_CHEMICALS2 5&PID_BIOGEL_ADV_NEW 1&PID_SUPER_STIMPAK 1&PID_BLUEPRINT_PID_HYPO 1@PID_MED_MACHINE 1@PID_HYPO 1@exp 5000 script fix_boy@fix_Blueprint}
{156}{}{PID_RADAWAY@Una solución química que se une con partículas de radiación y las pasa a través de su sistema. Toma tiempo para trabajar.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 130@PID_CHEMICALS 1&PID_BIO_GEL 1&PID_BROC_FLOWER 2&PID_BLUEPRINT_RADAWAY 1@PID_MED_MACHINE 1@PID_RADAWAY 1@exp 150 script fix_boy@fix_Blueprint}
{157}{}{PID_RAD_X@Químicos antirradiación a tomar antes de la exposición. No se conocen efectos secundarios.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 130@PID_CHEMICALS 1&PID_BIO_GEL 3&PID_XANDER_ROOT 2&PID_BLUEPRINT_RADX 1@PID_MED_MACHINE 1@PID_RAD_X 1@exp 300 script fix_boy@fix_Blueprint}
{158}{}{PID_MENTATS@Un pastillero de químicos que alteran la mente. Aumenta las funciones relacionadas con la memoria y acelera otros procesos mentales.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 130@PID_MUTATED_FRUIT 6&PID_CHEMICALS 2&PID_BLUEPRINT_MENTATS 1@PID_MED_MACHINE 1@PID_MENTATS 1@exp 160 script fix_boy@fix_Blueprint}
{159}{}{PID_BUFFOUT@Esteroides altamente avanzados. Mientras que en efecto, aumentan la fuerza y ​​los reflejos.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 150@PID_CHEMICALS 2&PID_MEAT_JERKY 5&PID_BLUEPRINT_BUFFOUT 1@PID_MED_MACHINE 1@PID_BUFFOUT 1@exp 350 script fix_boy@fix_Blueprint}
{160}{}{PID_PSYCHO@Un sistema de entrega único lleno de productos químicos extraños y desconocidos de origen probablemente militar. Se supone que aumenta el potencial de combate de un soldado.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 150@PID_SUPER_STIMPAK 1&PID_BIO_GEL 1&PID_CHEMICALS 2&PID_BLUEPRINT_PSYCHO 1@PID_MED_MACHINE 1@PID_PSYCHO 1@exp 280 script fix_boy@fix_Blueprint}
{161}{}{PID_JET@Jet es una potente metanfetamina que estimula el sistema nervioso central.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 150@PID_BRAHMINSHIT 1&PID_CHEMICALS 2&PID_EMPTY_JET 1&PID_BLUEPRINT_JET 1@PID_ADVANCED_BENCH 1@PID_JET 1@exp 150 script fix_boy@fix_Blueprint}
{162}{}{PID_GUM@After Burner es un potente chicle de metanfetamina que estimula el sistema nervioso central. La euforia inicial rara vez dura más de unos pocos minutos, pero durante ese tiempo, el usuario se llena de una oleada de energía y fuerza.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 150@PID_BIO_GEL 5&PID_CHEMICALS 1&PID_BLUEPRINT_GUM 1@PID_ADVANCED_BENCH 1@PID_GUM 1@exp 400 script fix_boy@fix_Blueprint}
{163}{}{PID_MUTIE@Un poderoso compuesto mutagénico diseñado para dar al usuario habilidades parecidas a las de un súper mutante. Tiene efectos secundarios muy desagradables.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 150@PID_CHEMICALS 2&PID_SCORPION_TAIL 2&PID_BLUEPRINT_MUTIE 1@PID_MED_MACHINE 1@PID_MUTIE 1@exp 200 script fix_boy@fix_Blueprint}
{164}{}{PID_VOODOO@Es una mezcla tribal, hecha de los subproductos sobrantes de varios bichos. Le otorga al usuario una mayor agilidad y una sensación de invencibilidad.@PE_PROFESSION_DOCTOR 2@PE_PROFESSION_DOCTOR 2&SK_DOCTOR 150@PID_WEAK_HEALING_POWDER 1&PID_GECKO_PELT 1&PID_BLUEPRINT_VOODOO 1@PID_MED_MACHINE 1@PID_VOODOO 1@exp 70 script fix_boy@fix_Blueprint}
{165}{}{PID_LIGHTER@Un encendedor de butano plateado, en buen estado.@@@PID_FLINT 1&PID_PUMP_PARTS 1&PID_METAL_PARTS 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_LIGHTER 1@exp 70 script fix_boy@fix_Generic}
{166}{}{PID_TENT@Una carpa apretada hecha de cuero de brahmín.@@@PID_BRAHMIN_HIDE 8&PID_ROPE 1&PID_SHARPENED_POLE 4@@PID_TENT 1@exp 400 script fix_boy@fix_Generic}
{167}{}{PID_LOCK@Una cerradura, bastante estándar para este entorno.@@@PID_FLINT 1&PID_METAL_PARTS 5@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_LOCK 1@exp 150 script fix_boy@fix_Generic}
{168}{}{PID_LOCKPICKS@Un conjunto de herramientas de cerrajería. Incluye todas las púas y llaves de tensión necesarias para abrir cerraduras convencionales de pasador y vaso.@@@PID_FLINT 1&PID_PUMP_PARTS 3&PID_METAL_PARTS 2@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_LOCKPICKS 1@exp 80 script fix_boy@fix_Generic}
{169}{}{PID_EXP_LOCKPICKS@Un conjunto de herramientas de cerrajería. Incluye todas las púas y llaves de tensión necesarias para abrir cerraduras convencionales de pasador y vaso. Este conjunto también incluye algunas herramientas especiales para mecanismos de bloqueo mecánico más difíciles.@@SK_LOCKPICK 125@PID_FLINT 1&PID_BRAHMIN_HIDE 1&PID_METAL_PARTS 7@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_EXP_LOCKPICK_SET 1@exp 260 script fix_boy@fix_Generic}
{170}{}{PID_ROPE@Una cuerda fuerte y gruesa. Cerca de 45 pies de largo.@@@PID_FIBER 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_ROPE 1@exp 5 script fix_boy@fix_Generic}
{171}{}{PID_WATERBAG_EMPTY@Esta bolsa se puede llenar con agua.@@@PID_BRAHMIN_HIDE 1&PID_FIBER 1@@PID_WATERBAG_EMPTY 1@exp 50 script fix_boy@fix_Generic}
{172}{}{PID_RADIO@Esta radio portátil no funciona pero parece que todavía está en bastante buenas condiciones.@@SK_REPAIR 100@PID_PUMP_PARTS 5&PID_METAL_PARTS 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_RADIO 1@exp 50 script fix_boy@fix_Generic}
{173}{}{PID_SHOVEL@Esta pala es propiedad de sus dueños. Ni siquiera puedes concebir un uso para ello.@@@PID_METAL_PARTS 1&PID_FIREWOOD 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_SHOVEL 1@exp 50 script fix_boy@fix_Generic}
{174}{}{PID_PRIMITIVE_TOOL@Esta herramienta más rudimentaria no parece muy confiable. Aún así, se puede usar para cortar madera o extraer mineral.@@@PID_FLINT 1@@PID_PRIMITIVE_TOOL 1@exp 15 script fix_boy@fix_Generic}
{175}{}{PID_AXE@Hacha desgastada. Su cuchilla todavía está en buenas condiciones.@@@PID_PUMP_PARTS 1&PID_FIREWOOD 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_AXE 1@exp 30 script fix_boy@fix_Generic}
{176}{}{PID_MULTI_TOOL@Un conjunto de herramientas que contiene varias herramientas útiles, incluidos los alicates.@@SK_REPAIR 150@PID_FLINT 1&PID_PUMP_PARTS 3&PID_METAL_PARTS 1@PID_WORKBENCH 1|PID_ADVANCED_BENCH 1@PID_MULTI_TOOL 1@exp 50 script fix_boy@fix_Generic}
{177}{}{PID_MOVABLE_AMMO_BOX_L1@Una caja de madera utilizada para almacenar munición.@@@PID_FIREWOOD 20&PID_FIBER 5&PID_METAL_PARTS2 4@@PID_MOVABLE_AMMO_BOX_L1 1@exp 500 script fix_boy@fix_Generic}
{178}{}{PID_MOVABLE_AMMO_BOX_S1@Una caja de madera utilizada para almacenar munición.@@@PID_FIREWOOD 10&PID_FIBER 2&PID_METAL_PARTS2 2@@PID_MOVABLE_AMMO_BOX_S1 1@exp 500 script fix_boy@fix_Generic}
{179}{}{PID_MOVABLE_POOR_BOX@Una pequeña caja utilizada para recolectar dinero para los pobres.@@@PID_FIREWOOD 5&PID_FIBER 3@@PID_MOVABLE_POOR_BOX 1@exp 10 script fix_boy@fix_Generic}
{180}{}{PID_MOVABLE_CHEST@Un cofre de madera.@@SK_REPAIR 50@PID_FIREWOOD 15&PID_FIBER 5@@PID_MOVABLE_CHEST 1@exp 20 script fix_boy@fix_Generic}
{181}{}{PID_MOVABLE_CRATE@Una caja de madera.@@SK_REPAIR 50@PID_FIREWOOD 10&PID_FIBER 5@@PID_MOVABLE_CRATE 1@exp 200 script fix_boy@fix_Generic}
{182}{}{PID_MOVABLE_FOOTLOCKER1@Casillero de piso básico. Almacena cosas, se sienta a los pies de la cama.@@SK_REPAIR 115@PID_METAL_PARTS2 2&PID_METAL_PARTS 8&PID_PUMP_PARTS 8@@PID_MOVABLE_FOOTLOCKER1 1@exp 500 script fix_boy@fix_Generic}
{183}{}{PID_MOVABLE_LOCKER1@Un contenedor de almacenamiento.@@SK_REPAIR 120@PID_METAL_PARTS2 2&PID_METAL_PARTS 12&PID_PUMP_PARTS 12@@PID_MOVABLE_LOCKER1 1@exp 500 script fix_boy@fix_Generic}
{184}{}{PID_MOVABLE_SAFE@Una caja fuerte de metal pesado.@@SK_REPAIR 120@PID_METAL_PARTS2 15&PID_ALLOYS2 5&PID_METAL_PARTS 10&PID_PUMP_PARTS 5@@PID_MOVABLE_SAFE 1@exp 825 script fix_boy@fix_Generic}
{185}{}{PID_MOVABLE_FRIDGE@Una nevera.@SK_SCIENCE 75@SK_SCIENCE 115@PID_PUMP_PARTS 10&PID_METAL_PARTS2 6&PID_ELECTRONIC_PARTS 3&PID_MICRO_FUSION_CELL 100@PID_MULTI_TOOL 1@PID_MOVABLE_FRIDGE 1@exp 500 script fix_boy@fix_Generic}
{186}{}{PID_MOTION_SENSOR@Un sensor de movimiento modelo Wattz Electronics C-U. Detecta el movimiento de material biológico a una distancia de pocos metros utilizando un dispositivo de radar sintonizado.@SK_SCIENCE 75@SK_SCIENCE 135@PID_FIBER 3&PID_METAL_PARTS2 6&PID_ELECTRONIC_PARTS 7&PID_MICRO_FUSION_CELL 20&PID_BLUEPRINT_SENSOR 1@PID_ADVANCED_BENCH 1@PID_MOTION_SENSOR 1@exp 2000 script fix_boy@fix_Generic}
{187}{}{PID_POWERED_ARMOR@Un traje autónomo de armadura con tecnología avanzada. Alimentado por un reactor de micro fusión, con suficiente combustible para durar cien años.@@PE_PROFESSION_ARMORER 2@PID_HIFLO 1&PID_PA_FUEL 1&PID_PA_SHELL 1&PID_ARM_POLYMER_ADV 5&PID_BLUEPRINT_POWERED_ARMOR 1@PID_MACHINERY_SMALL_GUNS 1@PID_POWERED_ARMOR 1@exp 100000 script fix_boy@fix_Blueprint}
{188}{}{PID_HARDENED_POWER_ARMOR@Una Armadura de Poder T-51b. El proceso de endurecimiento ha mejorado la capacidad defensiva de este sistema de armadura de alta tecnología.@@PE_PROFESSION_ARMORER 2@PID_POWERED_ARMOR 1&PID_PA_FUEL 1&PID_PA_SHELL 1&PID_SERVOMOTORS 1&PID_ARM_POLYMER_ADV 11&PID_BLUEPRINT_HARDENED_POWER_ARMOR 1@PID_MACHINERY_SMALL_GUNS 1@PID_HARDENED_POWER_ARMOR 1@exp 250000 script fix_boy@fix_Blueprint}
{189}{}{PID_ADVANCED_POWER_ARMOR@Esta armadura de poder avanzada está compuesta de aleaciones metálicas ligeras, reforzadas con piezas cerámicas en puntos clave. Los servomotores con asistencia de movimiento también parecen ser modelos de alta calidad.@@PE_PROFESSION_ARMORER 2@PID_ADVANCED_SHELL 2&PID_PA_FUEL 2&PID_ARM_CERAMIC 4&PID_ARM_POLYMER 12&PID_ARM_POLYMER_LASER 10&PID_ARM_POLYCARBONITE 1&PID_ARM_STEEL 6&PID_BLUEPRINT_ADVANCED_POWER_ARMOR 1@PID_MACHINERY_SMALL_GUNS 1@PID_ADVANCED_POWER_ARMOR 1@exp 1000000 script fix_boy@fix_Blueprint}
{190}{}{PID_ADVANCED_POWER_ARMOR_MK2@Esta armadura de poder parece estar compuesta completamente de compuestos cerámicos livianos en lugar de la combinación habitual de placas de metal y cerámica. Parece que debería brindar aún más protección que la armadura de poder avanzada estándar.@@PE_PROFESSION_ARMORER 2@PID_ADVANCED_SHELL 4&PID_PA_FUEL 4&PID_ADVANCED_POWER_ARMOR 1&PID_ARM_KEVLAR 3&PID_ARM_POLYMER_LASER 21&PID_ARM_CARBON 15&PID_ARM_GORETEX 4&PID_BLUEPRINT_ADVANCED_POWER_ARMOR_MK2 1@PID_MACHINERY_SMALL_GUNS 1@PID_ADVANCED_POWER_ARMOR_MK2 1@exp 2500000 script fix_boy@fix_Blueprint}
{191}{}{PID_ELECTRONIC_LOCKPICKS@Una ganzua electrónica Wattz Electronics Micromanipulator FingerStuff. Para vencer las cerraduras electrónicas y los dispositivos de seguridad.@@SK_LOCKPICK 200@PID_ELECTRIC_AMPLIFIER 1&PID_TECH_ELE_ENGINE 1&PID_METAL_PARTS 20@PID_ADVANCED_BENCH 1@PID_ELECTRONIC_LOCKPICKS 1@exp 15000 script fix_boy@fix_Generic}
{192}{}{PID_ELEC_LOCKPICK_MKII@Esta es la segunda generación de la ganzua electrónica Wattz Electronics Micromanipulator FingerStuff. Para derrotar cerraduras electrónicas y dispositivos de seguridad. Esta versión Mark II incluye software actualizado y herramientas de interfaz.@@SK_LOCKPICK 200@PID_ELECTRONIC_LOCKPICKS 1&PID_ELECTRIC_AMPLIFIER 1&PID_ARM_LEATHER_HIDE 1@PID_ADVANCED_BENCH 1@PID_ELEC_LOCKPICK_MKII 1@exp 25000 script fix_boy@fix_Generic}
{193}{}{PID_PLASMA_GATLING@A diferencia de la L30 Gatling Laser, este modelo no solo es completamente automático y tiene una mayor capacidad de munición, sino que también se produjo en masa para uso militar. Si bien entraron en servicio poco antes de la guerra, rápidamente se convirtieron en una parte importante del arsenal de facciones anteriores a la guerra.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_ROTARY_CHAMBER 1&PID_PLASMA_ACCELERATOR 2&PID_TECH_MECH_ENGINE 1&PID_TECH_ELE_WIRES 3&PID_TECH_PLASMA 2&PID_ARM_POLYCARBONITE 1&PID_BLUEPRINT_PLASMA_GATLING 1@PID_MACHINERY_SMALL_GUNS 1@PID_PLASMA_GATLING 1@exp 75000 script fix_boy@fix_Blueprint}
{194}{}{PID_POWER_HELMET@Un casco autónomo de armadura con tecnología avanzada. Parte esencial de la Armadura de Poder, protege bien contra golpes criticos.@@PE_PROFESSION_ARMORER 2@PID_ARM_STEEL 3&PID_ARM_CARBON 3&PID_BLUEPRINT_POWER_HELMET 1@PID_MACHINERY_SMALL_GUNS 1@PID_POWER_HELMET 1@exp 50000 script fix_boy@fix_Blueprint}
{195}{}{PID_HARDENED_POWER_HELMET@Un Casco de Poder T-51b. El proceso de endurecimiento ha mejorado la capacidad defensiva de este casco de alta tecnología.@@PE_PROFESSION_ARMORER 2@PID_POWER_HELMET 1&PID_ARM_GORETEX 4&PID_CARBON_POLYMER 2&PID_BLUEPRINT_HARDENED_POWER_HELMET 1@PID_MACHINERY_SMALL_GUNS 1@PID_HARDENED_POWER_HELMET 1@exp 100000 script fix_boy@fix_Blueprint}
{196}{}{PID_APA_HELMET@Este casco de poder avanzado está compuesto de aleaciones metálicas ligeras, reforzadas con piezas cerámicas en puntos clave. Este casco fue diseñado para proteger de disparos realmente fuertes.@@PE_PROFESSION_ARMORER 2@PID_ARM_CERAMIC 4&PID_ARM_POLYMER 2&PID_BLUEPRINT_ADVANCED_POWER_HELMET 1@PID_MACHINERY_SMALL_GUNS 1@PID_APA_HELMET 1@exp 100000 script fix_boy@fix_Blueprint}
{197}{}{PID_APA_HELMET_MK2@Este casco de poder avanzado parece estar compuesto completamente de compuestos cerámicos livianos en lugar de la combinación habitual de placas de metal y cerámica. Parece que debería brindar aún más protección que el casco de poder avanzado estándar.@@PE_PROFESSION_ARMORER 2@PID_ARM_GORETEX 7&PID_ARM_CARBON 5&PID_APA_HELMET 1&PID_BLUEPRINT_ADVANCED_POWER_HELMET_MK2 1@PID_MACHINERY_SMALL_GUNS 1@PID_APA_HELMET_MK2 1@exp 200000 script fix_boy@fix_Blueprint}
{198}{}{PID_WAKIZASHI_BLADE@Una espada artesanal fabricada con mucho cariño, el filo doble de esta la hace especial para penetrar armaduras.@@@PID_FLINT 1&PID_FIREWOOD 1&PID_METAL_PARTS2 3@PID_ADVANCED_BENCH 1@PID_WAKIZASHI_BLADE 1@exp 900 script fix_boy@fix_Generic}
{199}{}{PID_PLASMA_SMG@Un prototipo de arma de plasma de Wattz Electronics.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_ELECTRONIC_PARTS 3&PID_FIREWOOD 1&PID_ALLOYS2 4&PID_BLUEPRINT_PLASMA_SMG 1@PID_ADVANCED_BENCH 1@PID_PLASMA_SMG 1@exp 900 script fix_boy@fix_Generic}
{200}{}{PID_LASER_SPEAR@Este es un emisor láser conectado a una lanza afilada, una combinación de tradición y tecnologías modernas. Funciona oscilando un haz de energía directamente en frente de la cuchilla.@PE_PROFESSION_ENERGY_EXPERT 2@PE_PROFESSION_ENERGY_EXPERT 2@PID_ELECTRONIC_PARTS 2&PID_SHARP_SPEAR 1&PID_FIBER 1&PID_BLUEPRINT_LASER_SPEAR 1@PID_ADVANCED_BENCH 1@PID_LASER_SPEAR 1@exp 110 script fix_boy@fix_Generic}
{201}{}{PID_RAD_ROCKET@Tras la detonación, este cohete emite un fuerte pulso de radiación ionizante dañina.@@@PID_REFINED_ORE 2&PID_GUNPOWDER2 5@PID_ADVANCED_BENCH 1@PID_RAD_ROCKET 10@exp 300 script fix_boy@fix_Generic}
{202}{}{PID_SNEAK_ARMOR@@@PE_PROFESSION_ARMORER 2@PID_ARM_POLYMER 2&PID_ARM_POLYMER_ADV 2&PID_HIFLO 1&PID_ARM_GORETEX 1&PID_BLUEPRINT_SNEAK_ARMOR 1@PID_MACHINERY_SMALL_GUNS 1@PID_SNEAK_ARMOR 1@exp 500000 script fix_boy@fix_Blueprint}
{203}{}{PID_AK47@@@PE_PROFESSION_GUNSMITH_S 2@PID_CYLINDRICAL_LOCK 2&PID_TECH_SEMI_TRIGGER 1&PID_TECH_MICROCHIPS 1&PID_ARM_KEVLAR 1&PID_BLUEPRINT_AK47 1@PID_MACHINERY_SMALL_GUNS 1@PID_AK47 1@exp 500000 script fix_boy@fix_Blueprint}
{204}{}{PID_MEGA_SLEDGE@@@PE_PROFESSION_ENERGY_EXPERT 2@PID_ARM_KEVLAR 2&PID_CARBON_POLYMER 1&PID_SERVOMOTORS 2&PID_BLUEPRINT_MEGA_SLEDGE 1@PID_MACHINERY_SMALL_GUNS 1@PID_MEGA_SLEDGE 1@exp 500000 script fix_boy@fix_Blueprint}
{205}{}{PID_MFC_MK2@@@PE_PROFESSION_ENERGY_EXPERT 2@PID_PLASMA_ACCELERATOR 1&PID_TECH_ELE_ENGINE 1&PID_ELECTRONIC_PARTS 3&PID_BLUEPRINT_EFC 1@PID_MACHINERY_SMALL_GUNS 1@PID_MFC_MK2 100@exp 15000 script fix_boy@fix_Blueprint}
{206}{}{PID_HN_HEAL_NEEDLER_CARTRIDGE@@@PE_PROFESSION_DOCTOR 2@PID_BIOGEL_ADV_NEW 1&PID_CHEMICALS2 1&PID_GUNPOWDER2 3&PID_BLUEPRINT_HEALING_NEEDLER_AMMO 1@PID_MACHINERY_SMALL_GUNS 1@PID_HN_HEAL_NEEDLER_CARTRIDGE 100@exp 15000 script fix_boy@fix_Blueprint}
{207}{}{PID_MINE@@@PE_PROFESSION_DEMOLITION_EXPERT 2@PID_MINE_PART 1&PID_DETONATOR_PARTS 1&PID_GUNPOWDER3 1@PID_ADVANCED_BENCH 1@PID_MINE 1@exp 15000 script fix_boy@fix_Blueprint}
